In [1]:
#Numpy array iteration
import numpy as nu
a =nu.array([[1,2,3],[1,2,3],[1,2,3]])
print(a)
print("Array is iretaing")
for x in nu.nditer(a):
    print(x,end='')


[[1 2 3]
 [1 2 3]
 [1 2 3]]
Array is iretaing
123123123

In [6]:
#tranpose of the array
#terate over the transpose of the array
import numpy as np
a = np.array([[1,2,3,4,6],[4,5,6,7,6],[9,7,6,5,4]])
print(a)
print("Printing the tranpose of array")
#defalut method called
at=a.T
print(at)
for x in np.nditer(at):
    print(print("Iterating of the array"))
for x in np.nditer(a):
    print(x,end='')

[[1 2 3 4 6]
 [4 5 6 7 6]
 [9 7 6 5 4]]
Printing the tranpose of array
[[1 4 9]
 [2 5 7]
 [3 6 6]
 [4 7 5]
 [6 6 4]]
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
Iterating of the array
None
123464567697654

In [9]:
   #numpy Iterator treats the specific orders (F or C).
    import numpy as np  
      
    a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
      
    print("\nPrinting the array:\n")  
      
    print(a)  
      
    print("\nPrinting the transpose of the array:\n")  
    at = a.T  
      
    print(at)  
      
    print("\nIterating over the transposed array\n")  
      
    for x in np.nditer(at):  
        print(x, end= ' ')  
      
    print("\nSorting the transposed array in C-style:\n")  
      
    c = at.copy(order = 'C')  
      
    print(c)  
      
    print("\nIterating over the C-style array:\n")  
    for x in np.nditer(c):  
        print(x,end=' ')  
          
      
    d = at.copy(order = 'F')  
      
    print(d)  
    print("Iterating over the F-style array:\n")  
    for x in np.nditer(d):  
        print(x,end=' ')  


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transposed array in C-style:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array:

1 2 3 4 2 4 5 6 10 20 39 3 

In [12]:
#array valude modification
import numpy as np  
      
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("\nPrinting the original array:\n")  
print(a)  
      
print("\nIterating over the modified array\n")  
      
for x in np.nditer(a, op_flags = ['readwrite']):  
    x[...] = 3 * x;  
    print(x,end = ' ')  


Printing the original array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Iterating over the modified array

3 6 9 12 6 12 15 18 30 60 117 9 